-- MySQL Script generated by MySQL Workbench
-- Tue Dec 14 21:55:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nail_pos_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nail_pos_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nail_pos_dev` DEFAULT CHARACTER SET utf8 ;
USE `nail_pos_dev` ;

-- -----------------------------------------------------
-- Table `nail_pos_dev`.`asset_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`asset_user` (
  `uid` VARCHAR(36) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `email2` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `usertype` ENUM('ADMIN', 'DEV', 'OWNER', 'MANAGER', 'EMPLOYEE') NULL DEFAULT 'EMPLOYEE',
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NULL DEFAULT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `FK_user_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_user_update_idx` (`updated_by` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`asset_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`asset_location` (
  `uid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `zipcode` INT NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `phonenumber` VARCHAR(45) NULL DEFAULT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NULL DEFAULT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `FK_add_by_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_update_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_loc_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_loc_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`asset_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`asset_category` (
  `uid` VARCHAR(36) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `FK_cate_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_cate_update_idx` (`updated_by` ASC) VISIBLE,
  INDEX `FK_cate_location_id_idx` (`location_uid` ASC) VISIBLE,
  CONSTRAINT `FK_cate_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_cate_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_cate_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`asset_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`asset_department` (
  `uid` VARCHAR(36) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `FK_dept_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_dept_update_idx` (`updated_by` ASC) VISIBLE,
  INDEX `FK_dept_location_id_idx` (`location_uid` ASC) VISIBLE,
  CONSTRAINT `FK_dept_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_dept_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_dept_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`asset_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`asset_discount` (
  `uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NULL DEFAULT NULL,
  `description` VARCHAR(45) NOT NULL,
  `rate` FLOAT NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `FK_disc_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_disc_update_idx` (`updated_by` ASC) VISIBLE,
  INDEX `FK_disc_location_id_idx` (`location_uid` ASC) VISIBLE,
  CONSTRAINT `FK_disc_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_disc_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_disc_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`asset_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`asset_product` (
  `uid` VARCHAR(36) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `second_description` VARCHAR(255) NULL DEFAULT NULL,
  `third_description` VARCHAR(255) NULL DEFAULT NULL,
  `upc` TINYINT NULL DEFAULT '0',
  `item_code` TINYINT NULL DEFAULT '0',
  `cost` FLOAT NULL DEFAULT NULL,
  `price` FLOAT NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `FK_add_by_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_update_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_prod_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_prod_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`asset_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`asset_section` (
  `uid` VARCHAR(36) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NULL DEFAULT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `FK_sec_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_sec_update_idx` (`updated_by` ASC) VISIBLE,
  INDEX `FK_sec_location_id_idx` (`location_uid` ASC) VISIBLE,
  CONSTRAINT `FK_sec_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_sec_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_sec_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`asset_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`asset_tax` (
  `uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `rate` FLOAT NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `FK_tax_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_tax_update_idx` (`updated_by` ASC) VISIBLE,
  INDEX `FK_tax_location_id_idx` (`location_uid` ASC) VISIBLE,
  CONSTRAINT `FK_tax_addby`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_tax_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_tax_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_tax_updateby`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`asset_vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`asset_vendor` (
  `uid` VARCHAR(36) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NULL DEFAULT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `FK_ven_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_ven_update_idx` (`updated_by` ASC) VISIBLE,
  INDEX `FK_ven_location_id_idx` (`location_uid` ASC) VISIBLE,
  CONSTRAINT `FK_ven_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ven_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_ven_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`ref_location_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`ref_location_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ref_lp_product_id_idx` (`product_uid` ASC) VISIBLE,
  INDEX `FK_ref_lp_location_id_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_ref_lp_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_ref_lp_update_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_ref_lp_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ref_lp_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_ref_lp_product_id`
    FOREIGN KEY (`product_uid`)
    REFERENCES `nail_pos_dev`.`asset_product` (`uid`),
  CONSTRAINT `FK_ref_lp_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`ref_location_product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`ref_location_product_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_uid` VARCHAR(36) NULL DEFAULT NULL,
  `location_uid` VARCHAR(36) NULL DEFAULT NULL,
  `category_uid` VARCHAR(45) NULL DEFAULT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_product_id_idx` (`product_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpc_location_id_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpc_category_id_idx` (`category_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpc_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_ref_lpc_update_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_ref_lpc_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ref_lpc_category_id`
    FOREIGN KEY (`category_uid`)
    REFERENCES `nail_pos_dev`.`asset_category` (`uid`),
  CONSTRAINT `FK_ref_lpc_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_ref_lpc_product_id`
    FOREIGN KEY (`product_uid`)
    REFERENCES `nail_pos_dev`.`asset_product` (`uid`),
  CONSTRAINT `FK_ref_lpc_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`ref_location_product_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`ref_location_product_department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_uid` VARCHAR(36) NOT NULL,
  `department_uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `added_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NULL DEFAULT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ref_lpd_product_id_idx` (`product_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpd_location_id_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpd_dept_id_idx` (`department_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpd_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_ref_lpd_update_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_ref_lpd_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ref_lpd_dept_id`
    FOREIGN KEY (`department_uid`)
    REFERENCES `nail_pos_dev`.`asset_department` (`uid`),
  CONSTRAINT `FK_ref_lpd_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_ref_lpd_product_id`
    FOREIGN KEY (`product_uid`)
    REFERENCES `nail_pos_dev`.`asset_product` (`uid`),
  CONSTRAINT `FK_ref_lpd_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`ref_location_product_itemcode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`ref_location_product_itemcode` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `item_code` VARCHAR(45) NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ref_pi_product_id_idx` (`product_uid` ASC) VISIBLE,
  INDEX `FK_ref_pi_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_ref_pi_update_idx` (`updated_by` ASC) VISIBLE,
  INDEX `FK_ref_pi_location_id_idx` (`location_uid` ASC) VISIBLE,
  CONSTRAINT `FK_ref_pi_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ref_pi_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_ref_pi_product_id`
    FOREIGN KEY (`product_uid`)
    REFERENCES `nail_pos_dev`.`asset_product` (`uid`),
  CONSTRAINT `FK_ref_pi_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`ref_location_product_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`ref_location_product_section` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_uid` VARCHAR(36) NULL DEFAULT NULL,
  `section_uid` VARCHAR(36) NULL DEFAULT NULL,
  `location_uid` VARCHAR(36) NULL DEFAULT NULL,
  `added_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NULL DEFAULT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ref_lps_location_id_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_ref_lps_product_id_idx` (`product_uid` ASC) VISIBLE,
  INDEX `FK_ref_lps_section_id_idx` (`section_uid` ASC) VISIBLE,
  INDEX `FK_ref_lps_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_ref_lps_update_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_ref_lps_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ref_lps_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_ref_lps_product_id`
    FOREIGN KEY (`product_uid`)
    REFERENCES `nail_pos_dev`.`asset_product` (`uid`),
  CONSTRAINT `FK_ref_lps_section_id`
    FOREIGN KEY (`section_uid`)
    REFERENCES `nail_pos_dev`.`asset_section` (`uid`),
  CONSTRAINT `FK_ref_lps_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`ref_location_product_upc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`ref_location_product_upc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `upc` VARCHAR(45) NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ref_lpu_product_id_idx` (`product_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpu_location_id_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpu_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_ref_lpu_update_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_ref_lpu_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ref_lpu_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_ref_lpu_product_id`
    FOREIGN KEY (`product_uid`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ref_lpu_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`ref_location_product_vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`ref_location_product_vendor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_uid` VARCHAR(36) NOT NULL,
  `vendor_uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ref_lpv_location_id_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpv_product_id_idx` (`product_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpv_vendor_id_idx` (`vendor_uid` ASC) VISIBLE,
  INDEX `FK_ref_lpv_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_ref_lpv_update_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_ref_lpv_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ref_lpv_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_ref_lpv_product_id`
    FOREIGN KEY (`product_uid`)
    REFERENCES `nail_pos_dev`.`asset_product` (`uid`),
  CONSTRAINT `FK_ref_lpv_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ref_lpv_vendor_id`
    FOREIGN KEY (`vendor_uid`)
    REFERENCES `nail_pos_dev`.`asset_vendor` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`ref_location_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`ref_location_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `relation_reason` ENUM('CREATED', 'EMPLOYED') NULL DEFAULT 'EMPLOYED',
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_user_id_idx` (`user_uid` ASC) VISIBLE,
  INDEX `FK_location_uid_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_ref_lu_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_ref_lu_update_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_location_uid`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_ref_lu_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_ref_lu_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_user_uid`
    FOREIGN KEY (`user_uid`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`)
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`ref_product_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`ref_product_discount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `discount_uid` VARCHAR(36) NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_rpd_product_id_idx` (`product_uid` ASC) VISIBLE,
  INDEX `FK_rpd_location_id_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_rpd_discount_id_idx` (`discount_uid` ASC) VISIBLE,
  INDEX `FK_rpd_add_by_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_rpd_update_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_rpd_add_by`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_rpd_discount_id`
    FOREIGN KEY (`discount_uid`)
    REFERENCES `nail_pos_dev`.`asset_discount` (`uid`),
  CONSTRAINT `FK_rpd_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_rpd_product_id`
    FOREIGN KEY (`product_uid`)
    REFERENCES `nail_pos_dev`.`asset_product` (`uid`),
  CONSTRAINT `FK_rpd_update_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`ref_product_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`ref_product_tax` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `tax_uid` VARCHAR(36) NOT NULL,
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_rpt_product_id_idx` (`product_uid` ASC) VISIBLE,
  INDEX `FK_rpt_location_id_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_rpt_tax_id_idx` (`tax_uid` ASC) VISIBLE,
  INDEX `FK_rpt_add_by_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_rpt_update_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_rpt_add_by`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_rpt_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_rpt_product_id`
    FOREIGN KEY (`product_uid`)
    REFERENCES `nail_pos_dev`.`asset_product` (`uid`),
  CONSTRAINT `FK_rpt_tax_id`
    FOREIGN KEY (`tax_uid`)
    REFERENCES `nail_pos_dev`.`asset_tax` (`uid`),
  CONSTRAINT `FK_rpt_update_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`trans_checkout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`trans_checkout` (
  `uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `quantity` FLOAT NOT NULL DEFAULT '0',
  `sub_total` FLOAT NOT NULL DEFAULT '0',
  `discount_total` FLOAT NOT NULL DEFAULT '0',
  `tax_total` FLOAT NOT NULL DEFAULT '0',
  `void_qty` FLOAT NOT NULL DEFAULT '0',
  `void_amount` FLOAT NOT NULL DEFAULT '0',
  `refund_qty` FLOAT NOT NULL DEFAULT '0',
  `refund_amount` FLOAT NOT NULL DEFAULT '0',
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `FK_trans_c_location_id_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_trans_c_add_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_trans_c_update_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_trans_c_add`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_trans_c_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_trans_c_update`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nail_pos_dev`.`trans_checkout_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nail_pos_dev`.`trans_checkout_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checkout_uid` VARCHAR(36) NOT NULL,
  `location_uid` VARCHAR(36) NOT NULL,
  `product_uid` VARCHAR(36) NOT NULL,
  `apply_tax` TINYINT NOT NULL DEFAULT '1',
  `apply_discount` TINYINT NOT NULL DEFAULT '0',
  `is_refund` TINYINT NOT NULL DEFAULT '0',
  `is_void` TINYINT NOT NULL DEFAULT '0',
  `added_datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` TIMESTAMP NULL DEFAULT NULL,
  `added_by` VARCHAR(36) NOT NULL,
  `updated_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_trans_cd_checkout_id_idx` (`checkout_uid` ASC) VISIBLE,
  INDEX `FK_trans_cd_location_id_idx` (`location_uid` ASC) VISIBLE,
  INDEX `FK_trans_cd_product_id_idx` (`product_uid` ASC) VISIBLE,
  INDEX `FK_trans_cd_add_by_idx` (`added_by` ASC) VISIBLE,
  INDEX `FK_trans_cd_update_by_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK_trans_cd_add_by`
    FOREIGN KEY (`added_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`),
  CONSTRAINT `FK_trans_cd_checkout_id`
    FOREIGN KEY (`checkout_uid`)
    REFERENCES `nail_pos_dev`.`trans_checkout` (`uid`),
  CONSTRAINT `FK_trans_cd_location_id`
    FOREIGN KEY (`location_uid`)
    REFERENCES `nail_pos_dev`.`asset_location` (`uid`),
  CONSTRAINT `FK_trans_cd_product_id`
    FOREIGN KEY (`product_uid`)
    REFERENCES `nail_pos_dev`.`asset_product` (`uid`),
  CONSTRAINT `FK_trans_cd_update_by`
    FOREIGN KEY (`updated_by`)
    REFERENCES `nail_pos_dev`.`asset_user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `nail_pos_dev` ;

-- -----------------------------------------------------
-- procedure sp_clean_all_table
-- -----------------------------------------------------

DELIMITER $$
USE `nail_pos_dev`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `sp_clean_all_table`(

)
BEGIN
    SET FOREIGN_KEY_CHECKS = 0;
	DELETE FROM asset_category;
    DELETE FROM asset_department;
    DELETE FROM asset_discount;
    DELETE FROM asset_location;
    DELETE FROM asset_product;
    DELETE FROM asset_section;
    DELETE FROM asset_tax;
    DELETE FROM asset_user;
    DELETE FROM asset_vendor;
    DELETE FROM ref_location_product;
    ALTER TABLE ref_location_product auto_increment = 1;
    DELETE FROM ref_location_product_category;
    ALTER TABLE ref_location_product_category auto_increment = 1;
    DELETE FROM ref_location_product_department;
    ALTER TABLE ref_location_product_department auto_increment = 1;
    DELETE FROM ref_location_product_itemcode;
    ALTER TABLE ref_location_product_itemcode auto_increment = 1;
    DELETE FROM ref_location_product_section;
    ALTER TABLE ref_location_product_section auto_increment = 1;
    DELETE FROM ref_location_product_upc;
    ALTER TABLE ref_location_product_upc auto_increment = 1;
    DELETE FROM ref_location_product_vendor;
    ALTER TABLE ref_location_product_vendor auto_increment = 1;
    DELETE FROM ref_location_user;
    ALTER TABLE ref_location_user auto_increment = 1;
    DELETE FROM trans_checkout;
    ALTER TABLE trans_checkout auto_increment = 1;
    DELETE FROM trans_checkout_detail;
    ALTER TABLE trans_checkout_detail auto_increment = 1;
	SET FOREIGN_KEY_CHECKS = 1;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
